name: 'Action test'
description: 'learning how to use outputs'

inputs:
  val:
    description: 'input to be printed'
    required: true

outputs:
  result:
    description: 'it is the step result'

runs:
  using: 'composite'
  steps:
    - name: say hello
      shell: bash
      run: echo "Hello my friend"
    - name: print val
      shell: bash
      run: echo ${{inputs.val}}
    - name: set return value
      id: my-action
      shell: bash
      run: |
        echo SETTING VALUES TO OUTPUT
        echo "The result is: ${inputs.val}"
        echo "result=${{inputs.val}}" >> $GITHUB_OUTPUT
