name: POC Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      input1:
        description: "Input 1"
        required: true
        default: "default input 1 value"
      input2:
        description: "Input 2"
        required: true
        default: "default input 2 value"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: print input 1
        id: first-step
        run: echo "input1 ${{ inputs.input1 }}"
      - name: print before step status
        run: echo ${{steps.first-step.outcome}}
      - name: print input 2
        run: echo "input2 ${{ inputs.input2 }}"
      - name: print using action
        uses: ./.github/actions/my_action
        with:
          val: "Mike"
      - name: Usar el output de la acción
        env:
          result: ${{ steps.my-action.outputs.result }}
        run: echo "El resultado de la acción es ${{result}}"
