name: POC Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      input1:
        description: "Input 1"
        required: true
        default: "default input 1 value"
      input2:
        description: "Input 2"
        required: true
        default: "default input 2 value"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print input 1
        id: first-step
        run: echo "input1 ${{ inputs.input1 }}"
      - name: print input 2
        run: echo {{steps.first-step.outcome}}
        run: echo "input2 ${{ inputs.input2 }}"
