name: POC Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      input1:
        description: "Input 1"
        required: true
        default: "default input 1 value"
      input2:
        description: "Input 2"
        required: true
        default: "default input 2 value"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-job-result.outputs.result }}
    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4
      - name: print input 1
        id: first-step
        run: echo "input1 ${{ inputs.input1 }}"
      - name: print before step status
        run: echo ${{steps.first-step.outcome}}
      - name: print input 2
        run: echo "input2 ${{ inputs.input2 }}"
      - name: print using action
        id: actioner
        uses: ./.github/actions/my_action
        with:
          val: "Mike"
      - name: Usar el output de la acci贸n
        shell: bash
        env:
          result: ${{ steps.actioner.outputs.result }}
        run: echo "El resultado de la acci贸n es $result"
      - name: set job result
        id: set-job-result
        env:
          result: ${{ steps.actioner.outputs.result }}
        run: echo "result=$result" >> $GITHUB_ENV
  
  confirm:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: validate previous step
        shell: bash
        env:
          result: ${{ needs.build.outputs.result }}
        run: echo "El resultado de la acci贸n es $result"

